export const MOCK_TRANSACTIONS = [
  {
    userId: "cc2d3b39-e59d-4b8d-8f82-85b96ffc6137",
    socialAccountId: "1",
    source: "youtube",
    name: "Youtube ad sense",
    amount: 100,
    currency: "USD",
    status: "cleared",
    paymentMethod: "PayPal",
    isRecurring: true,
  },
  {
    userId: "cc2d3b39-e59d-4b8d-8f82-85b96ffc6137",
    socialAccountId: "2",
    source: "Twitch",
    name: "Twitch Subscriptions",
    amount: 140,
    currency: "USD",
    status: "cleared",
    paymentMethod: "ACH",
    isRecurring: false,
  },
  {
    userId: "cc2d3b39-e59d-4b8d-8f82-85b96ffc6137",
    socialAccountId: "3",
    source: "tiktok",
    name: "TikTok shop purchase",
    amount: 30,
    currency: "USD",
    status: "cleared",
    paymentMethod: "PayPal",
    isRecurring: false,
  },
  {
    userId: "cc2d3b39-e59d-4b8d-8f82-85b96ffc6137",
    socialAccountId: "4",
    source: "amazon",
    name: "Amazon affiliate",
    amount: 120,
    currency: "USD",
    status: "cleared",
    paymentMethod: "PayPal",
    isRecurring: false,
  },
  {
    userId: "cc2d3b39-e59d-4b8d-8f82-85b96ffc6137",
    socialAccountId: "5",
    source: "shopify",
    name: "Customer purchase",
    amount: 28,
    currency: "USD",
    status: "cleared",
    paymentMethod: "PayPal",
    isRecurring: false,
  },
  {
    userId: "cc2d3b39-e59d-4b8d-8f82-85b96ffc6137",
    socialAccountId: "6",
    source: "amazon",
    name: "Amazon affiliate",
    amount: 86,
    currency: "USD",
    status: "cleared",
    paymentMethod: "PayPal",
    isRecurring: false,
  },
  {
    userId: "cc2d3b39-e59d-4b8d-8f82-85b96ffc6137",
    socialAccountId: "7",
    source: "tiktok",
    name: "Creator fund",
    amount: 1000,
    currency: "USD",
    status: "cleared",
    paymentMethod: "PayPal",
    isRecurring: false,
  },
  {
    userId: "cc2d3b39-e59d-4b8d-8f82-85b96ffc6137",
    socialAccountId: "8",
    source: "shopify",
    name: "Customer purchase",
    amount: 20,
    currency: "USD",
    status: "pending",
    paymentMethod: "ACH",
    isRecurring: false,
  },
  {
    userId: "cc2d3b39-e59d-4b8d-8f82-85b96ffc6137",
    socialAccountId: "9",
    source: "youtube",
    name: "youtube subscription",
    amount: 350,
    currency: "USD",
    status: "cleared",
    paymentMethod: "PayPal",
    isRecurring: false,
  },
  {
    userId: "cc2d3b39-e59d-4b8d-8f82-85b96ffc6137",
    socialAccountId: "10",
    source: "tiktok",
    name: "Creator fund",
    amount: 560,
    currency: "USD",
    status: "pending",
    paymentMethod: "PayPal",
    isRecurring: false,
  },
  {
    userId: "cc2d3b39-e59d-4b8d-8f82-85b96ffc6137",
    socialAccountId: "11",
    source: "Twitch",
    name: "Twitch subscription",
    amount: 233,
    currency: "USD",
    status: "failed",
    paymentMethod: "PayPal",
    isRecurring: false,
  },
  {
    userId: "cc2d3b39-e59d-4b8d-8f82-85b96ffc6137",
    socialAccountId: "12",
    source: "Twitch",
    name: "Twitch subscription",
    amount: 320,
    currency: "USD",
    status: "cleared",
    paymentMethod: "ACH",
    isRecurring: true,
  },
  {
    userId: "cc2d3b39-e59d-4b8d-8f82-85b96ffc6137",
    socialAccountId: "13",
    source: "youtube",
    name: "Youtube ad sense",
    amount: 411,
    currency: "USD",
    status: "cleared",
    paymentMethod: "ACH",
    isRecurring: false,
  },
  {
    userId: "cc2d3b39-e59d-4b8d-8f82-85b96ffc6137",
    socialAccountId: "14",
    source: "shopify",
    name: "Customer purchase",
    amount: 34,
    currency: "USD",
    status: "pending",
    paymentMethod: "PayPal",
    isRecurring: false,
  },
  {
    userId: "cc2d3b39-e59d-4b8d-8f82-85b96ffc6137",
    socialAccountId: "15",
    source: "shopify",
    name: "Customer purchase",
    amount: 22,
    currency: "USD",
    status: "cleared",
    paymentMethod: "PayPal",
    isRecurring: false,
  },
  {
    userId: "cc2d3b39-e59d-4b8d-8f82-85b96ffc6137",
    socialAccountId: "16",
    source: "tiktok",
    name: "Creator fund",
    amount: 510,
    currency: "USD",
    status: "cleared",
    paymentMethod: "ACH",
    isRecurring: false,
  },
  {
    userId: "cc2d3b39-e59d-4b8d-8f82-85b96ffc6137",
    socialAccountId: "17",
    source: "amazon",
    name: "Amazon affiliate",
    amount: 25,
    currency: "USD",
    status: "cleared",
    paymentMethod: "PayPal",
    isRecurring: false,
  },
  {
    userId: "cc2d3b39-e59d-4b8d-8f82-85b96ffc6137",
    socialAccountId: "18",
    source: "tiktok",
    name: "Creator fund",
    amount: 670,
    currency: "USD",
    status: "cleared",
    paymentMethod: "PayPal",
    isRecurring: false,
  },
  {
    userId: "cc2d3b39-e59d-4b8d-8f82-85b96ffc6137",
    socialAccountId: "19",
    source: "shopify",
    name: "Customer purchase",
    amount: 58,
    currency: "USD",
    status: "cleared",
    paymentMethod: "ACH",
    isRecurring: true,
  },
  {
    userId: "cc2d3b39-e59d-4b8d-8f82-85b96ffc6137",
    socialAccountId: "20",
    source: "amazon",
    name: "Amazon affiliate",
    amount: 54,
    currency: "USD",
    status: "cleared",
    paymentMethod: "PayPal",
    isRecurring: false,
  },
  {
    userId: "cc2d3b39-e59d-4b8d-8f82-85b96ffc6137",
    socialAccountId: "21",
    source: "tiktok",
    name: "TikTok shop purchase",
    amount: 12,
    currency: "USD",
    status: "cleared",
    paymentMethod: "ACH",
    isRecurring: false,
  },
  {
    userId: "cc2d3b39-e59d-4b8d-8f82-85b96ffc6137",
    socialAccountId: "22",
    source: "youtube",
    name: "Youtube ad sense",
    amount: 50,
    currency: "USD",
    status: "cleared",
    paymentMethod: "PayPal",
    isRecurring: false,
  },
  {
    userId: "cc2d3b39-e59d-4b8d-8f82-85b96ffc6137",
    socialAccountId: "23",
    source: "youtube",
    name: "Youtube ad sense",
    amount: 59,
    currency: "USD",
    status: "failed",
    paymentMethod: "PayPal",
    isRecurring: false,
  },
  {
    userId: "cc2d3b39-e59d-4b8d-8f82-85b96ffc6137",
    socialAccountId: "24",
    source: "amazon",
    name: "Amazon affiliate",
    amount: 23,
    currency: "USD",
    status: "cleared",
    paymentMethod: "ACH",
    isRecurring: true,
  },
  {
    userId: "cc2d3b39-e59d-4b8d-8f82-85b96ffc6137",
    socialAccountId: "25",
    source: "tiktok",
    name: "TikTok shop purchase",
    amount: 45,
    currency: "USD",
    status: "cleared",
    paymentMethod: "PayPal",
    isRecurring: false,
  },
  {
    userId: "cc2d3b39-e59d-4b8d-8f82-85b96ffc6137",
    socialAccountId: "26",
    source: "youtube",
    name: "youtube subscription",
    amount: 304,
    currency: "USD",
    status: "pending",
    paymentMethod: "PayPal",
    isRecurring: false,
  },
  {
    userId: "cc2d3b39-e59d-4b8d-8f82-85b96ffc6137",
    socialAccountId: "27",
    source: "youtube",
    name: "youtube subscription",
    amount: 290,
    currency: "USD",
    status: "cleared",
    paymentMethod: "PayPal",
    isRecurring: false,
  },
  {
    userId: "cc2d3b39-e59d-4b8d-8f82-85b96ffc6137",
    socialAccountId: "28",
    source: "shopify",
    name: "Customer purchase",
    amount: 43,
    currency: "USD",
    status: "cleared",
    paymentMethod: "ACH",
    isRecurring: false,
  },
  {
    userId: "cc2d3b39-e59d-4b8d-8f82-85b96ffc6137",
    socialAccountId: "29",
    source: "youtube",
    name: "Youtube ad sense",
    amount: 231,
    currency: "USD",
    status: "cleared",
    paymentMethod: "PayPal",
    isRecurring: false,
  },
  {
    userId: "cc2d3b39-e59d-4b8d-8f82-85b96ffc6137",
    socialAccountId: "30",
    source: "youtube",
    name: "Youtube ad sense",
    amount: 542,
    currency: "USD",
    status: "cleared",
    paymentMethod: "PayPal",
    isRecurring: true,
  },
  {
    userId: "cc2d3b39-e59d-4b8d-8f82-85b96ffc6137",
    socialAccountId: "31",
    source: "youtube",
    name: "Youtube ad sense",
    amount: 342,
    currency: "USD",
    status: "cleared",
    paymentMethod: "PayPal",
    isRecurring: false,
  },
  {
    userId: "cc2d3b39-e59d-4b8d-8f82-85b96ffc6137",
    socialAccountId: "32",
    source: "youtube",
    name: "Youtube ad sense",
    amount: 420,
    currency: "USD",
    status: "cleared",
    paymentMethod: "ACH",
    isRecurring: false,
  },
  {
    userId: "cc2d3b39-e59d-4b8d-8f82-85b96ffc6137",
    socialAccountId: "33",
    source: "youtube",
    name: "Youtube ad sense",
    amount: 223,
    currency: "USD",
    status: "pending",
    paymentMethod: "PayPal",
    isRecurring: false,
  },
  {
    userId: "cc2d3b39-e59d-4b8d-8f82-85b96ffc6137",
    socialAccountId: "34",
    source: "youtube",
    name: "Youtube ad sense",
    amount: 442,
    currency: "USD",
    status: "cleared",
    paymentMethod: "PayPal",
    isRecurring: false,
  },
  {
    userId: "cc2d3b39-e59d-4b8d-8f82-85b96ffc6137",
    socialAccountId: "35",
    source: "youtube",
    name: "Youtube ad sense",
    amount: 1257,
    currency: "USD",
    status: "cleared",
    paymentMethod: "PayPal",
    isRecurring: false,
  },
  {
    userId: "cc2d3b39-e59d-4b8d-8f82-85b96ffc6137",
    socialAccountId: "36",
    source: "youtube",
    name: "Youtube ad sense",
    amount: 1420,
    currency: "USD",
    status: "pending",
    paymentMethod: "PayPal",
    isRecurring: false,
  },
  {
    userId: "cc2d3b39-e59d-4b8d-8f82-85b96ffc6137",
    socialAccountId: "37",
    source: "youtube",
    name: "Youtube ad sense",
    amount: 1680,
    currency: "USD",
    status: "cleared",
    paymentMethod: "ACH",
    isRecurring: false,
  },
  {
    userId: "cc2d3b39-e59d-4b8d-8f82-85b96ffc6137",
    socialAccountId: "38",
    source: "youtube",
    name: "Youtube ad sense",
    amount: 1542,
    currency: "USD",
    status: "cleared",
    paymentMethod: "PayPal",
    isRecurring: false,
  },
  {
    userId: "cc2d3b39-e59d-4b8d-8f82-85b96ffc6137",
    socialAccountId: "39",
    source: "youtube",
    name: "Youtube ad sense",
    amount: 1222,
    currency: "USD",
    status: "cleared",
    paymentMethod: "PayPal",
    isRecurring: false,
  },
  {
    userId: "cc2d3b39-e59d-4b8d-8f82-85b96ffc6137",
    socialAccountId: "40",
    source: "youtube",
    name: "Youtube ad sense",
    amount: 1260,
    currency: "USD",
    status: "pending",
    paymentMethod: "PayPal",
    isRecurring: false,
  },
  {
    userId: "cc2d3b39-e59d-4b8d-8f82-85b96ffc6137",
    socialAccountId: "41",
    source: "youtube",
    name: "Youtube ad sense",
    amount: 310,
    currency: "USD",
    status: "cleared",
    paymentMethod: "PayPal",
    isRecurring: false,
  },
  {
    userId: "cc2d3b39-e59d-4b8d-8f82-85b96ffc6137",
    socialAccountId: "42",
    source: "youtube",
    name: "Youtube ad sense",
    amount: 5392,
    currency: "USD",
    status: "failed",
    paymentMethod: "PayPal",
    isRecurring: false,
  },
  {
    userId: "cc2d3b39-e59d-4b8d-8f82-85b96ffc6137",
    socialAccountId: "43",
    source: "youtube",
    name: "Youtube ad sense",
    amount: 1070,
    currency: "USD",
    status: "cleared",
    paymentMethod: "ACH",
    isRecurring: false,
  },
  {
    userId: "cc2d3b39-e59d-4b8d-8f82-85b96ffc6137",
    socialAccountId: "44",
    source: "youtube",
    name: "Youtube ad sense",
    amount: 239,
    currency: "USD",
    status: "cleared",
    paymentMethod: "ACH",
    isRecurring: false,
  },
  {
    userId: "cc2d3b39-e59d-4b8d-8f82-85b96ffc6137",
    socialAccountId: "45",
    source: "youtube",
    name: "Youtube ad sense",
    amount: 1290,
    currency: "USD",
    status: "cleared",
    paymentMethod: "PayPal",
    isRecurring: false,
  },
  {
    userId: "cc2d3b39-e59d-4b8d-8f82-85b96ffc6137",
    socialAccountId: "46",
    source: "youtube",
    name: "Youtube ad sense",
    amount: 1242,
    currency: "USD",
    status: "cleared",
    paymentMethod: "PayPal",
    isRecurring: true,
  },
  {
    userId: "cc2d3b39-e59d-4b8d-8f82-85b96ffc6137",
    socialAccountId: "47",
    source: "youtube",
    name: "Youtube ad sense",
    amount: 1973,
    currency: "USD",
    status: "cleared",
    paymentMethod: "ACH",
    isRecurring: false,
  },
  {
    userId: "cc2d3b39-e59d-4b8d-8f82-85b96ffc6137",
    socialAccountId: "48",
    source: "youtube",
    name: "Youtube ad sense",
    amount: 422,
    currency: "USD",
    status: "pending",
    paymentMethod: "ACH",
    isRecurring: false,
  },
  {
    userId: "cc2d3b39-e59d-4b8d-8f82-85b96ffc6137",
    socialAccountId: "49",
    source: "youtube",
    name: "Youtube ad sense",
    amount: 1203,
    currency: "USD",
    status: "cleared",
    paymentMethod: "PayPal",
    isRecurring: false,
  },
  {
    userId: "cc2d3b39-e59d-4b8d-8f82-85b96ffc6137",
    socialAccountId: "50",
    source: "youtube",
    name: "Youtube ad sense",
    amount: 1002,
    currency: "USD",
    status: "cleared",
    paymentMethod: "PayPal",
    isRecurring: false,
  },
];
